### ISSUE TITLE
Hyrax - Make role idempotent 

### ISSUE THREAD

**Issue by cudevmaxwell** [cu-library/hyrax-ansible#17]

**Comment by cudevmaxwell** [comment]
Can `bundle exec rails generate hyrax:install -f` be run safely multiple times? If not, should it be run after each version bump?

**Comment by cudevmaxwell** [comment]
Three commands need to be run after installation is complete:

`bundle exec rails hyrax:default_collection_types:create`
`bundle exec rails hyrax:default_admin_set:create`
`bunde exec rails hyrax:workflow:load` 

These commands could be included in the playbook if they could be made idempotent. Does that mean we'll need to check the output of a SQL command?

**Comment by cudevmaxwell** [comment]
There are a lot of `changed_when: False` directives in the hyrax role. For example: 

```
- name: Add Hyrax to Gemfile
  command: "/usr/local/bin/bundle add hyrax --version={{ hyrax_version }}"
  args:
    chdir: /var/www/hyrax/hyrax-root
  become: yes
  become_user: hyrax
  changed_when: False
```

Can we use the output or error code of `bundle` instead of hardcoding 'false'?

**Comment by cudevmaxwell** [comment]
Pretty sure we can run `bundle exec rails hyrax:default_collection_types:create` and `bundle exec rails hyrax:default_admin_set:create` without affecting an existing install. `changed_when: False` could be appropriate for those calls.

**Comment by cudevmaxwell** [comment]
By idempotent, I mean all tasks should only run when they have to (using `creates`, for example) or have been checked to ensure they can be safely run over and over again without altering the state of a running system. Those tasks can be indicated as safe by using `changed_when: False`.

**Comment by cudevmaxwell** [comment]
```
- name: Gem install rails
  shell: "/usr/local/bin/gem install rails --version={{ rails_version }}"
  args:
    creates: "/usr/local/bin/rails"
```

This step is idempotent, because of the `creates` argument. However, it should run again if the `rails_version` variable is bumped. This affects #36

**Comment by cudevmaxwell** [comment]
```
- name: Run rails generate hyrax:install
  command: /usr/local/bin/bundle exec rails generate hyrax:install -f
  args:
    chdir: /var/www/hyrax/hyrax-root
  become: yes
  become_user: hyrax
```

This generator is available here: https://github.com/samvera/hyrax/blob/master/lib/generators/hyrax/install_generator.rb 

Can we run this over and over again? How does `insert_into_file` work? If we can find a 'creates' target, we'll need to run this task on Hyrax version bump. Maybe test Gemfile and register a 'new_hyrax_version' variable for things that need to be done after a new Hyrax version?

**Comment by cudevmaxwell** [comment]
```
- name: Run db migrate
  command: /usr/local/bin/bundle exec rails db:migrate
  args:
    chdir: /var/www/hyrax/hyrax-root
  become: yes
  become_user: hyrax
  environment:
    SECRET_KEY_BASE: "{{ hyrax_secret_key_base }}"
    HYRAX_POSTGRESQL_PASSWORD: "{{ hyrax_postgresqldatabase_user_password }}"
    RAILS_ENV: production
```

Pretty sure this is idempotent, and we can add `changed_when: False`.
