### ISSUE TITLE
Nginx - Will updating package recreate default config

### ISSUE THREAD

**Issue by cudevmaxwell** [cu-library/hyrax-ansible#2]
In the past, we've left default.conf around but commented out. That way the package won't overwrite the file on update. 

Currently, the playbook does this instead:

```yaml
- name: Delete default config [CentOS]
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  when: ansible_distribution == "CentOS"

- name: Delete symbolic link to default config [Debian/Ubuntu]
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  when: ansible_os_family == "Debian"
```

Will these default configs return when Nginx is updated?
